### ISSUE TITLE
Serious problems occurred when training cls network with dcn

### ISSUE THREAD

**Issue by zhanglonghao1992** [unsky/Deformable-ConvNets#30]
I tried to train a classification net using dcn (ResNet-50 with dcn in stage 5).
I view feature maps of the deformable conv layer and find that it cannot learn any useful things. Actually the content on each feature map is either 0 or a fixed constant.
I am wondering if there is a problem with the code or dcn is hard to train on the classification task.
@unsky  Do you have time to have a look at my classification network and maybe discuss this phenomenon with me？Thank you very much！
Here is my qq：819375556

**Comment by zhanglonghao1992** [comment]
@unsky I also check out the offset that detection model(faster rcnn with ResNet50) learned. Its too small, like 1e-2~1e-3. It seems like the offset does not play any role...

**Comment by lucinyaLi** [comment]
> @unsky I also check out the offset that detection model(faster rcnn with ResNet50) learned. Its too small, like 1e-2~1e-3. It seems like the offset does not play any role...

hello~ do you find the reason of the above-mentioned phenomenon?
